### ISSUE TITLE
Replace tuple constants with variables in Omega Visitor

### ISSUE THREAD

**Issue by riftEmber** [BoiseState-AdaptLab/IEGenLib#22]
As a pre-processing step to the Omega Visitor, constant values in tuples will be replaced with variables, and an equality constraint added to the Set/Relation between the new variable and the old constant value. For example, the Set `{[0,i,j,k]} ` would become `{[t0,i,j,k]: t0 = 0}`.

**Comment by tpops** [comment]
The restriction in IEGenLib for changing tuple declaration of conjunctions is pretty intense
//! If replacing a constant with a variable ignores the substitution                 
//! in that conjunction.
Tuple Declaration Constants can’t be replaced by a variable in IEGenLib

**Comment by tpops** [comment]
Workaround the restriction is to create a totally new Conjunction with the modified tupleDeclaration. This feature is added to the OmegaVisitor, by overriding the previsitConjunction. 

When a conjunction is pre-visited, the conjunction tuple declaration is checked for constants
Constants are replaced with tuple variables and equality constraints get created for each replacement

**Comment by tpops** [comment]
Done. Test cases add to computation_test

**Comment by riftEmber** [comment]
:+1:

**Comment by cathieO** [comment]
Adding documentation of example that will work vs. example that does not work.
Incorrect:
```
symbolic NR, rowptr_0(2), rowptr_1(2);
I:={ [0, i, k] : i >= 0 && k - rowptr_0(0,i) >= 0 && -i + NR - 1 >= 0 && -k + rowptr_1(0,i) - 1 >= 0 && c=0 };
R:={[0, i,k]->[0, i,k]};
codegen R : I;
```
Correct:
```
symbolic NR, rowptr_0(2), rowptr_1(2);
I:={ [c, i, k] : i >= 0 && k - rowptr_0(c,i) >= 0 && -i + NR - 1 >= 0 && -k + rowptr_1(c,i) - 1 >= 0 && c=0 };
R:={[c, i,k]->[c, i,k]};
codegen R : I;
```

**Comment by cathieO** [comment]
Based on our discussion @tpops will be adding a few more test cases to make sure that we can handle sets that have several constants (for example, [0,i,2,j,1])
