### ISSUE TITLE
Codegen warnings: extra tokens at end of #undef directive 

### ISSUE THREAD

**Issue by rvishnkr** [BoiseState-AdaptLab/IEGenLib#23]
Generated code displays the following warnings for all #undef:

`warning: extra tokens at end of #undef directive
 #undef s1()
`

**Comment by riftEmber** [comment]
Perhaps stating the obvious but this is due to the extraneous parenthesis after the name of the macro, I'll fix it sometime

**Comment by riftEmber** [comment]
Should be fixed
