### ISSUE TITLE
renaming UF during postvisit

### ISSUE THREAD

**Issue by cathieO** [BoiseState-AdaptLab/IEGenLib#4]
We need to only rename the UF if it is a new usage of the UF. This will require some infrastructure to keep track of current uses.

**Comment by riftEmber** [comment]
Does this apply to UF calls that are rewritten to have a different number of arguments? For example, under the current implementation the call `A(i+j)` would get changed to `A_0(i,j)` with the macro `#define A_0(p0, p1) A(p0+p1)`. The call `A(i)` would get changed to `A_0(i)` with the macro `#define A_0(p0) A(p0)`. Although A is the same function with arity one, the two versions of `A_0` end up with different arity. Should they be considered the same function?

**Comment by cathieO** [comment]
Not quite. It means that if there are say 3 uses of UF as A(i) that there is only a single A defined. If there are 3 uses of UF as A(i) and 3 uses of UF as A(i+1) then there are only two UFs defined. As I read the code there would be 6. does that clarify?

**Comment by riftEmber** [comment]
That makes sense. So would UFs be considered distinct on the basis of which tuple variable they use, or just what is done with the variable -- would `A(i)` and `A(j)` be distinct?

**Comment by cathieO** [comment]
Just based on the expression. Names don't matter. Now that I've written that I am feeling uncomfortable, so be prepared for me to course correct later, maybe. I need to build an example.

**Comment by riftEmber** [comment]
How is the prefix issue handled with Relations, which have both an input and output tuple? Should it be prohibited to use variables from both in one UF call?

**Comment by riftEmber** [comment]
Also, would toString comparison be a valid way to compare if two UF calls are the same? Since printing is standardized and absolutely any difference between calls would make them different

**Comment by riftEmber** [comment]
This feature is mostly completed in 00e05dfd7ed6fc402df38d10b2c8af4888ecb3ca , barring the issue of tuple prefixes in Relations
