### ISSUE TITLE
(undo) Project Out Modifications 

### ISSUE THREAD

**Issue by tpops** [BoiseState-AdaptLab/IEGenLib#51]
#### Goal:

ProjectOut on Set/Relation should have a boolean variable that lets the caller decide to take out the tuple variable or not during projection.

```cpp
Relation::ProjectOut(int tv, bool shouldRemove = true /*Setting the default to true reduces */);
Set::ProjectOut(int tv, bool shouldRemove = true);
```

The variable `shouldRemove` could be anything.

#### Code Section To Focus On:

file: [set_relation.cc:151](https://github.com/BoiseState-AdaptLab/IEGenLib/blob/1c85781b4c24a3c745944f686d0d1583942c9571/src/set_relation/set_relation.cc#L151) has the code section that takes out the tuple variable projected from ISL. ISL does not take out the tuple variable. Bypassing this is key.

There are some other code sections that should be modified too as the shouldRemove function should propagate all the way to `islSetProjectOut`. And I believe @riftEmber will be able to handle this propagation.

`VisitorProjectOut` and `VisitorProjectOutCleanUp` has to be modifed as well.

**Comment by riftEmber** [comment]
Decided we don't need this. Need to revert changes to projectOut, except for expanded unit testing for original functionality.

**Comment by riftEmber** [comment]
Done, but projectOut tests are still failing with the new UF support. Need to figure out what the correct expected result is.

**Comment by riftEmber** [comment]
Meeting update: it seems that the failing tests are due to an issue within TransitiveClosure's simplification process. @tpops is going to investigate further, but it's a separate issue
