### ISSUE TITLE
[toOmegaString] Relations With 0 Input Arity Error

### ISSUE THREAD

**Issue by tpops** [BoiseState-AdaptLab/IEGenLib#6]
When toOmegaString is called on a relation with 0 input arity and some output arity, your function currently returns {[<output arity>]} this makes Omega recognize this string as Set, not a Relation. This should be fixed as execution schedules for single instance statements would not be correctly generated.

Example:

``` cpp
auto relation = IEGenLib::Relation("{[]->[0,0,0,0,0]}");
std::string omegaString = relation->toOmegaString();
// omegaString in this case returns "{[0,0,0,0,0]}".
// This recognized in omega as a set, not a relation.
// What toOmegaString should be returning should be "{[]->[0,0,0,0,0]}", this way 
// omega can recognize this as a relation with input arity 0 and output arity 5.
```

**Comment by riftEmber** [comment]
Closed by 3caa36917f4018f8c00a3cfef9848bd30b5a5ee0
